version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db-postgres-pruebas
    networks:
      - app-network-public
    restart: always
    environment:
      POSTGRES_USER: oscar
      POSTGRES_PASSWORD: chia60
      POSTGRES_DB: test_db
      TZ: America/Toronto
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /c/docker/shared:/usr/shared

networks:
  app-network-public:
    driver: bridge

volumes:
  pgdata:

