version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db-postgres-pruebas
    networks:
      - app-network-public
    restart: always
    environment:
      POSTGRES_USER: oscar
      POSTGRES_PASSWORD: chia60
      POSTGRES_DB: test_db
      TZ: America/Toronto
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /c/docker/shared:/usr/shared

  redis:
    image: "redis:6.2.10"  # Specific stable version of Redis
    container_name: redis-container-pruebas
    networks:
      - app-network-public
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

networks:
  app-network-public:
    driver: bridge

volumes:
  pgdata:
  redis_data:

